#nullable enable
using System;

namespace ScreenReaderMod.Common.Systems.MenuNarration;

internal sealed partial class MenuUiSelectionTracker
{
    private const int CharacterCreationTabCount = 10;

    private static readonly string?[] HairStyleDescriptions =
    {
        "Large, wild, messy hair,",
        "Small, tousled, messy hair,",
        "Forward-combed hair with two lifted strands and a long pointed beard,",
        "Short, flat, anvil-shaped flattop,",
        "Short hair that falls forward and covers the face,",
        "Bangs with a small ponytail; hair falls over the face,",
        "Long, thick, curly braid,",
        "Short cut with straight bangs,",
        "Forward swooping fringe,",
        "Heavy bangs with an L-shaped ponytail,",
        "Huge, towering mohawk,",
        "Round, circular space buns,",
        "Curly dreadlocks that drape over the face,",
        "Medium-length messy hair,",
        "Forward-combed hair with two lifted strands,",
        "Completely bald,",
        "Very large, rounded afro,",
        "Neatly combed hair with a short beard,",
        "Bangs paired with a curly ponytail,",
        "Short swooping hair with a center part,",
        "Wizard-hat-like style with two back points and a center part,",
        "Bangs with a tiny curled ponytail,",
        "Bowl-like front with a long wavy ponytail,",
        "Spiky, Sonic-the-Hedgehog-style hair,",
        "Center-parted hair with two swoops to the left,",
        "Princess-Leia-style side buns,",
        "Combed hair with bangs and a small ponytail,",
        "Old-world men's ponytail, historical style,",
        "Combed, lifted, Elvis-like pompadour,",
        "Bowl-style cut with a high, long, straight ponytail,",
        "Windswept, combed-back hair,",
        "Wavy, spiked hair with tapered sides,",
        "Small pigtails with bangs,",
        "Shoulder-length thin braids,",
        "Tight, closely braided hair,",
        "Small, spiked-up cut reminiscent of Sam from Stardew Valley,",
        "Bowl-shaped, umbrella-like mop style,",
        "Large Johnny-Bravo-style pompadour,",
        "Large, long, straight ponytail with wavy texture,",
        "A-line bob,",
        "Pronounced middle part, curled front strand, face-covering bob,",
        "Side-covering bob with a curl and center part,",
        "Side-covering bob with a right swoop and center part,",
        "Fiery, spiky ponytail with a partially covered eye; Super-Saiyan-like,",
        "Diagonal part with a curled bob,",
        "Straight, angled Karen cut with a diagonal part,",
        "Medium curly ponytail with bangs,",
        "Long high ponytail with bangs,",
        "Braided bun,",
        "Very short, flat bob,",
        "Medium curly ponytail with bangs,",
        "Straight hair with bangs, a forehead peak, and a Y-shaped back section,",
        "Shaved side with a front pompadour and unibrow,",
        "Bushy, messy, puffed-out hair,",
        "Short-to-medium hair with leaf-shaped bangs,",
        "Long straight hair with leaf-shaped pointed bangs,",
        "Long, straight hair with a full Jesus-style beard,",
        "Medium straight hair with a full Jesus-style beard,",
        "Short, center-parted hair with a Jesus-style beard,",
        "Very short hair with a diagonal part and a Jesus beard,",
        "Bangs with a center part, C-shaped style, and short beard,",
        "Short hair with a front part, a left strand, and a chin-strap beard,",
        "Fancy center-parted hair with a beard and mustache,",
        "Long, wavy Jesus-style hair and beard,",
        "Long straight hair with leaf-shaped bangs and Y-shaped fringe,",
        "Long straight hair with a tucked front braid,",
        "Long hair parted in the middle with a twist at the back,",
        "Medium straight hair with a front part,",
        "Diagonally parted long straight hair with curtain bangs,",
        "Wavy hair covering the left eye with a front part,",
        "Medium hair with a widow's peak and ear clearance,",
        "Medium straight hair with leaf-shaped bangs and a center part,",
        "Long straight hair covering one eye with a strong center part,",
        "Long chunky braid with curtain bangs and center part,",
        "Short hair with an evil curled mustache and pointed beard,",
        "Short centered hair with a long curled mustache,",
        "Bald head with eyebrows and a goatee,",
        "Short hair with a middle part and thin curled mustache,",
        "Short ponytail with a front part, side V-shape, and left-eye covering strand,",
        "Short ponytail with blunt bangs and fluffy texture,",
        "Very long ponytail with a scrunchie,",
        "Two long pigtails with curled front strands and a center part,",
        "Short, straight, deeply parted hair with bangs,",
        "Thick, fox-ear-shaped bangs with a spiraled ponytail,",
        "Puffy, shoulder-length hair with pronounced bangs,",
        "Middle-parted Lara-Croft-style braid,",
        "Huge wavy ponytail with a Y-shaped part and covered eye,",
        "Very long, wavy, side-covering hair,",
        "Side-swept, curly hair,",
        "Side-swept braided style with blunt straight bangs,",
        "Medium curly pigtails with straight blunt bangs,",
        "Low medium ponytail with blunt bangs,",
        "Four thick backward-facing spikes on each side,",
        "Short straight hair in two rounded sections,",
        "Asian-style topknot with shaved sides and small mustache,",
        "Medium straight hair with a strong center part and messy texture,",
        "Picard-style monk ring,",
        "Bowl-like winter-hat shape with a raised bun,",
        "Medium straight afro,",
        "Combed-back afro,",
        "Medium afro with a short beard,",
        "Long, fluffy, curly hair,",
        "Medium curly hair with bangs,",
        "Long curly hair with leaf-shaped bangs,",
        "Short hair with a small front part,",
        "Short, front-parted bowl cut,",
        "Long, fluffy, wavy hair with bangs and an ahoge,",
        "Neatly combed rounded style,",
        "Bald with an ahoge,",
        "Tightly pulled-back short ponytail with visible eyebrow,",
        "Curly bob with an ahoge,",
        "Short, side-swept dreads,",
        "Long, side-swept dreads,",
        "Fancy curled, combed style,",
        "Short, flat style with pronounced bangs in two sections,",
        "Shaved side with very short bangs,",
        "Shaved side with very short bangs and beard stubble,",
        "Short combed hair with shaved side, small beard, and mustache,",
        "Rounded short hair with long thin mustache and beard,",
        "Short hair with small swoops, short beard, and mustache,",
        "Very short hair with a long thin beard,",
        "Rounded combed style with a short full beard,",
        "Rounded, combed hair with side shave and mutton chops,",
        "Cone-like wizard-hat-inspired layered style,",
        "Short curled ram-horn-like hair,",
        "Alien probe-shaped style,",
        "UFO-shaped style,",
        "Medusa-like snake-hair design,",
        "Cluster of many bulb-shaped hair circles,",
        "Geometric style parted diagonally into three sections,",
        "Short bowl cut,",
        "Wild, large Super-Saiyan-like spikes,",
        "Medium mohawk with shaved sides and Predator-style locks,",
        "Long wavy hair with pronounced bangs and an ahoge,",
        "Rock-star-like long wavy hair with pronounced bangs,",
        "Short straight cut with ear gap, bangs, and diagonal part,",
        "Shaved side with short pulled-back ponytail and triangular beard,",
        "Short hair with a pronounced middle part,",
        "Short, flat, Johnny-Bravo-style shape with ear gap,",
        "Monk/Picard style with a small beard,",
        "Mullet with outward-curling ends,",
        "Short diagonal-part style with bangs,",
        "Short puffy hair with thick bangs,",
        "Puffy winter-hat-like style with a loose bun,",
        "Very short buzz cut,",
        "Curly pigtail space buns with curled bangs,",
        "Long layered wavy hair with a tiny ahoge,",
        "Short combed style with a shaved side and medium beard,",
        "Fluffy short hair with a curl on top, diagonal part, and small beard,",
        "Short spiky hair with diagonal part and small beard - Roxas-style,",
        "Short messy rounded hair with a small beard,",
        "Rounded combed style with ear gap and medium beard,",
        "Balding head with mutton chops and large beard,",
        "Short flat cut with mutton chops and medium beard,",
        "Mohawk with small ahoge and long beard,",
        "Rounded combed style with a top point and medium beard - Rhett-like,",
        "Fancy swirled combed style with ear gap and small beard,",
        "Messy rounded hair with center part and long beard,",
        "Short rounded hair with center part and long beard,",
        "Short combed pointy style with medium beard and mutton chops,",
        "Balding head with thin ponytail and mutton chops,",
        "Short center-parted hair with bangs, ear gap, and small beard with mutton chops,",
        "Medium wavy hair with a medium ponytail and bangs,",
        "Giant crab-claw-shaped hairstyle,",
        "Spiked bangs with long curly ponytail and short ahoge,",
    };
}
